### ISSUE TITLE
Define the response codes for unsupported media type

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-framework-spec#21]
During the setup of the Produces in the framework, we define what we should allow in the Accept method but do not define the error codes to return if it is outside this.  

We need to define in the spec what error codes to return when.  The one I am talking about here would return in my opinion a 406 Not Acceptable error code.

**Comment by robertjd** [comment]
If the client requests a resource that the framework integration is handling, but the requested content type is not in the `produces` list, then yes I believe the response should be 406.  @lhazlewood ?

**Comment by robertjd** [comment]
Here is a good read on this:

http://stackoverflow.com/questions/12130910/how-to-interpret-empty-http-accept-header

As such, I think the rules should be:
- If no `Accept` header, or the value of `Accept` is null, then treat it as `Accept: */*` and return the HTML response.
- If `Accept` is something that we truly do not support, e.g. `Accept: foo/bar`, then send 406.

**Comment by lhazlewood** [comment]
We can do what we want here.  The HTTP spec allows us to either return a 406 or return a representation instead if we want:

https://tools.ietf.org/html/rfc7231#section-3.4

Specifically, 2nd-to-last paragraph of 3.4.1, 'Proactive Negotiation' (bold emphasis is mine):

> A user agent cannot rely on proactive negotiation preferences being
>    consistently honored, since **the origin server** might not implement
>    proactive negotiation for the requested resource or **might decide that
>    sending a response that doesn't conform to the user agent's
>    preferences is better than sending a 406 (Not Acceptable) response.**

So, we get to choose.

My opinion is that if the client has an Accept header that does not contain _any_ value that reflects what the server can support, that 406 is returned to let the client know it's just not possible.  Returning a representation (media type) of something that the client hasn't indicated as supported could cause an error on the client (or not - who knows), so I think I prefer to be explicit in this particular area.

**Comment by lhazlewood** [comment]
I should note that my answer above is based on the latest/current version of the HTTP spec, while the SO answer references the old RFC 2616.  I don't know if they differ, but I chose to avoid the old reference and focus only on RFC 7231.
