### ISSUE TITLE
It should be possible to dynamically specify the authority part (i.e. host and port) of verification and password reset URLs

### ISSUE THREAD

**Issue by george-hawkins-work** [stormpath/stormpath-framework-spec#22]
Currently the base part of verification and password reset URLs for a given directory are specified as a hardcoded **fixed** values:
![image](https://cloud.githubusercontent.com/assets/12233059/12020071/336c5b48-ad78-11e5-8623-4d98562e85bd.png)
However we hit the same Stormpath directories from a few different sites (each with their own hostname).

So if the link base URL for a given directory points to siteX and someone hits the "I forgot my password" link on one of the other sites using the same directory, e.g. siteY, they get a URL to handle the password reset that takes them to siteX rather than siteY.

It would be nice if the site could be dynamically specified in the account creation and password reset `POST` requests.

At the moment we have e.g. `http://dev/` and `http://uat/` but password reset URLs triggered via either always direct you to `uat` as both share the same directory and the link base URL for that directory is hard coded currently to point to `uat`.

**Comment by robertjd** [comment]
Thank you for this feedback.  At the moment this is a limitation of the API: directory resources have a single base URL for each email template.  This is not something we will solve in the framework integration.

To work around the issue, you can do one of the following:
- Use multiple directories, one for each site, if you don't need to use the same account (username and password combo) across each site
- Use ID Site, with Organizations and subdomains, to use domain-specific login but share directories.  See [Using ID Site For  Multi-Tenancy](https://docs.stormpath.com/guides/using-id-site/#using-id-site-for-multitenancy)
- Use our SDK to create the forgot password token, then use your email service of choice to send your own email to the user.

Please let us know if we can assist by contacting us at support@stormpath.com.  As this is not something we will solve in the framework integrations, I am closing this issue.  Thanks again!
