### ISSUE TITLE
Logout behavior is missing from the spec

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-framework-spec#25]
For example:

curl -v -H "Authorization: Bearer eyJraWQiOiJSOTJTQkhKQzFVNERBSU1HUTNNSE9HVk1YIiwiYWxnIjoiSFMyNTYifQ.eyJqdGkiOiIzME9iRVpvc3pXOUlieHZaU0JQbmdIIiwiaWF0IjoxNDU0NDM1ODMyLCJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy82dkZUNEFSZldDbXVIVlY4Vmt0alRvIiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy80V1NjTWJBbm8zVjk1aWlTc3dralBYIiwiZXhwIjoxNDU0NDM5NDMyLCJydGkiOiIzME9iRVdVbzR2cUp6OHBpRnZZWDREIn0.TcalI7xhHfSLwUpbx_IJ6nXJfZwNa63vpxlYsXg2Q5Q" http://localhost:8080/logout

The logout route MUST delete the access token and refresh token for the bearer token or access token cookie

**Comment by edjiang** [comment]
What is this in context for mobile? Does the route revoke the access/refresh tokens, too?

**Comment by lhazlewood** [comment]
It should.  Any logout endpoint should completely relinquish any/all identity and/or session state to be safe.
