### ISSUE TITLE
When we handle the forget password pages

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-framework-spec#3]
We need to make sure we do not leak an account's status or information

**Comment by robertjd** [comment]
This did make it into the spec, but now that we've implemented it: this doesn't make sense.  Yes, this prevents a dictionary attack through the `/forgot` endpoint, but we be expose the same attack vector through `/login`, so I don't see a point in limiting the information that we return from the `/forgot` endpoint

**Comment by rdegges** [comment]
+1 super annoying.... ><

**Comment by rdegges** [comment]
We are changing this in our express stuff right now, and this is gonna be really annoying for people.

**Comment by lhazlewood** [comment]
Annoying how?

And how does `/forgot` allow dictionary attacks when you have to send and respond to an email to reset your password?  I.e. "If you have a user account, you should see an email soon with instructions."

**Comment by robertjd** [comment]
@lhazlewood which side of situation are you promoting?

**Comment by lhazlewood** [comment]
I'm not promoting either side - just trying to understand what is annoying and why. :)

**Comment by robertjd** [comment]
A few annoyances:
- As an end user, I may think I have an account in the system, but I don't.  I keep putting in my email address, getting a message that says an email is being sent, an I never get an email.  An error message, "no account found" , would be a MUCH nicer experience
- As a developer or support tech, I want to know why the password reset is failing for the user.  Error messages are nice here too

**Comment by robertjd** [comment]
Per our discussion this morning, we will implement this as an option.  By default we will not expose the error which indicates that the email address does not exist.  You will have to enable an option if you want to inform the user that the email address cannot be found in the data store.
