### ISSUE TITLE
Usage of “login” over “username”

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-framework-spec#36]
We made the choice to have clients post a “login” field, rather than a “username” field.  The reasoning is that “login” is better because this value can be a username _or_ an email address, as such it felt wrong to call it just `username`.

However, this breaks away from the REST API.  If you don't supply the `username` field to the `loginAttempts` endpoint, you'll get the error `username parameter cannot be null, empty, or blank.`.  This will be confusing because it now says `username` and not `login`. In the error message.

As I see it, the best solution is to have an error handler in the framework which supplies a better error message.

Or to do away with the `login` idea.. ?

**Comment by rdegges** [comment]
I'm not really a fan of the 'username' thing -- I think it was a mistake to have that as part of the core API as it is very confusing, and is going to be more confusing when we eventually make more and more core fields optional.

So, I suppose I'm in favor of keeping the 'login' thing instead :( Although I know that would be super annoying ><

**Comment by nbarbettini** [comment]
I agree that "login" makes more sense than "username". Intercepting the error message feels icky to me, but that seems like the only viable option. Unless someone has a better idea, I'm for it.

**Comment by robertjd** [comment]
I would also prefer to keep `login`, and deal with the error shim until the REST API changes.

**Comment by edjiang** [comment]
Slightly off topic, but I would disagree with `login` as a term for the account identifier, as it's ambiguous as whether or not it's a noun or verb. We use it as a verb in many other contexts, including the route itself.

"We need to collect the user's login on the login page" is a confusing statement and one that I could see customer developers saying with this naming strategy.

**Comment by edjiang** [comment]
For instance, here is some documentation I just wrote and am trying to make less confusing. 

## 3. Logging in

To log in, collect the login and password from the user, and then pass them to login method:

``` Swift
Stormpath.sharedSession.login(login, password: password) { (success, error) -> Void in
    guard error == nil else {
        // We could not authenticate the user with the given credentials. Handle the error. 
        return
    }
    // The user is now logged in, and the Stormpath access token will now be set!
}
```

**Comment by omgitstom** [comment]
I would rather you guys not build custom logic for stuff that is minor.  Perfection is the enemy of progress, and the more logic we have to put in the integrations is just slowing everything down.  No one is done with their framework to spec, this doesn't impact spec, if the error message changes on the server, then there is no change to be done here.

This is minor, treat it as such.  We can fix this in the API, but it is low on the totem pole as well.

**Comment by robertjd** [comment]
Thanks everyone for the input, no changes needed as I see it.
