### ISSUE TITLE
No Expansion on /me endpoint

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-framework-spec#37]
Talking with @omgitstom, the decision for expansion was removed for the /me endpoint.  This needs to be updated in the web-config.yml and user-context.md files

**Comment by edjiang** [comment]
Isn't that covered in 00255c0?

**Comment by bretterer** [comment]
that commit adds in the expansion option.  Talking to Tom, the decision was set into motion to remove the ability to specify expand options.  @edjiang

**Comment by edjiang** [comment]
I believe that's referring to the `?expand=X` query parameter; we are removing that.

https://github.com/stormpath/stormpath-framework-spec/commit/00255c09671de079f837f1c6edee24239a4c45a7#diff-cefc0f204f2da890e70c70316d9a1292L70

**Comment by bretterer** [comment]
Ping @omgitstom

**Comment by robertjd** [comment]
We removed the ability for a client to request the `/me` route and specify an expansion as a query parameter.  We still want to allow the developer to opt-in to expansion with static configuration.

**Comment by bretterer** [comment]
This ticket was more for the addition or subtraction of the spec.  right
now it talks about the expansion parameters.

**Comment by edjiang** [comment]
Nothing was changed with the configuration portion of the spec. If a user expands options in the client, it will be exposed on the endpoint.
