### ISSUE TITLE
Implement logout as POST

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-framework-spec#43]
There is a strong argument that the logout URI should not respond to GET requests, because:
- Other sites can maliciously log you out via simple image tags.  E.g. http://superlogout.com/ :)
- The omnibar in the browser will pre-emptibely request the logout URI if it thinks you are typing it, and log you out.

More reading here: 

http://stackoverflow.com/questions/3521290/logout-get-or-post

As such, I believe we should switch to using POST instead.

**Comment by lhazlewood** [comment]
Unless I'm missing something, POST doesn't really solve anything.  Anyone could use Javascript to auto-submit a form that sends a POST to the /logout URI as well.

Isn't this more of a CSRF issue?

I should note that IMO this is not really a security problem - a logout should clear/eliminate any security context whatsoever, which just prevents the user from doing anything.  It would be a nuisance however.

**Comment by robertjd** [comment]
Correct, the issue here is mostly UX nuisance.  To absolutely prevent someone from logging you out, without your permission, you would need a CSRF solution with your POST forms.
