### ISSUE TITLE
Clarification of nullable bool types

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-framework-spec#46]
It would be helpful to have some comments in [web-config.yaml](https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml) or elsewhere describing which `bool` values are allowed to be `null`, and which aren't.

**Comment by robertjd** [comment]
I see that `basePath` has no comments, and the null's in the cookie definitions are just a link to another document.  Are there others that need more clarification?

**Comment by nbarbettini** [comment]
`basePath` is fine - I assumed that any string types can be null.

No other clarification is needed, if none of the other bools can be set to null.

**Comment by lhazlewood** [comment]
I'd use `baseUri` for consistency and to be congruent (so it is obvious that uris are concatenated)

**Comment by nbarbettini** [comment]
I have no further concerns on this issue, other than addressing @lhazlewood's comment above. Do we want to change the base config name from `basePath` to `baseUri`?
