### ISSUE TITLE
How should frameworks respond to an incorrect verb?

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-framework-spec#57]
I was thinking about this in the context of #56 but realized the question applies to the entire spec.

There are a number of routes that only support GET and not POST, or vice versa:
- `/oauth/token` - POST
- `/me` - GET
- `/logout` - POST

If an incorrect verb is used, should the framework respond with `405`, `404`, or something else? This also applies to how the framework should handle verbs like PUT, DELETE, PATCH, etc.

**Comment by bretterer** [comment]
405 should be reported if the endpoint exists, but does not respond to the verb

404 should be reported if the endpoint does not exist.

**Comment by nbarbettini** [comment]
:+1: Agreed. Created a new document to clarify this, see this PR: #59
