### ISSUE TITLE
Regarding Produces & SPA Configuration

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-framework-spec#62]
Hey all, I've been digging into the implementation of our recent decisions regarding the produces option and I'm having some issues.

I don’t believe our framework should be responsible for serving someone’s SPA entry path.  I believe that should be the responsibility of the developer. If someone is using Stormpath with a SPA, all they need (and want) is the JSON API that allows them to use login, registration, etc.  Why should an authentication library be handling my SPA for me?

As such, I don’t think we should be responding with 406 when a browser is requesting text/html, but only application/json has been place in the produces list.  In this situation I think we should pass on the request, and assume that something else (that the developer has configured) will render the HTML response (the SPA entry).

**Comment by nbarbettini** [comment]
I haven't voiced an opinion yet on the SPA functionality, because I haven't yet implemented it in my framework. I did have some concerns, though, around how exactly it would work. If the Stormpath middleware is first in the pipeline, and a web server is second, why should the former be responsible for serving up general HTML pages? (The HTML views still make sense, because they are a special case IMO.)

So, I agree that we should revisit this.

Perhaps the behavior of "terminate" vs. "pass-through" should be configurable. I don't know if it should **only** be a side-effect of the order/contents of `produces`.

**Comment by robertjd** [comment]
Okay guys, this is an epic walk-through of the developer experience around SPA support.

Ground rules: “asset pipeline” = “my web framework has some magical way for me to tell it where my SPA is, and that it should serve it as the default view for my website”

As of now we’ve designed a content negotiation scheme, because our library can render JSON or HTML views for the routes that we handle.  In that respect, our design is correct and serves the correct content type, based on the ordering of the types in the Accept header.

However, I’m going to argue that we should break this.  The whole point of the `produces` and `spa` options were not to make an HTTP 1.1 compliant response framework.  They were meant to make it easier for a developer to integrate their SPA with Stormpath.  

Our current design falls short because it requires the developer to tell us where their SPA file is located.  I’ve never felt great about this, because in practice there are many ways in which a developer may serve their SPA application and we should not need to know how this is done.  We should simply support a pure JSON API if that’s all the developer needs.  This was the original intention for content negotiation.  The alternative is a different URL scheme, such as `/api/login`, but I would prefer to not do this - it feels much nicer to have a single `/login` URL.

The primary developer stories that we need to support are:
- **(1) I just want a JSON interface that my front-end library can use, I already have an asset pipeline for my SPA**
- **(2) I want the /login URL to serve my SPA, but when I post to it I want Stormpath to handle the login post.**

When trying to support these stories, we had this problem:
- **(A) How can we know if the developer wants our default HTML pages, or their SPA root?**
- **(B) What do we call the option that allows them to disable HTML responses?**

In response, we created the “produces” option for (B) and for (A) we decided to require the developer to manually opt-in to a `spa.view` configuration, so that we could know what they want.  

As such the configuration to support story (1) looks like this:

``` yaml
stormpath:
  web:
    produces:
      - application/json
```

This looked okay on the surface, but in practice there is a problem: if the developer’s asset pipeline (that serves the SPA) is run AFTER our login controller has run, they won’t be able to respond with their SPA because our library will have already responded to the request with a JSON view model, because the browsers Accept header will accept JSON as well as HTML.

Thus, to achieve (1) you need to do the following:

``` yaml
stormpath:
  web:
    produces:
      - application/json
    spa:
      enabled: true
      view: index  # or other value that indicates where the entry is
```

But now this is frustrating, because the developer has to configure our library to do something that their asset pipeline is probably already doing for them.

Coming back to story (2), we felt that the only way to achieve that story was to have the developer tell us where the SPA is.  But in practice, most SPA developers have a “catchall” configuration that will simply serve the SPA for any HTML GET request that is not handled by some more specific controller (such as the Stormpath login controller, in the Stormpath framework integration).

As such, I believe we need to change course in the following ways:
- The produces option is meant to be used for turning of HTML responses, and for changing the default response type when no Accept header is present, or Accept is `*/*`.
- We should “pass” on a request if we can’t fulfill it as HTML, we should not 406.  Thus we assume that the developer is going to handle the HTML response for the given route.

To achieve the desired user stories, without requiring the SPA root to be defined, we would have to implement the following decision tree:

```
                   Is Accept Header
                   undefined or */* ?
                        |
                +-------+-------+
                |               |
               Yes              No
                |               |
           Serve first          |
           type in produces     |
           config               |
                                |
                              Is HTML in
                            Accept Header?
                                |
                +---------------+---------------+
                |                               |
               Yes                              No
                |                               |
              Is HTML                         Is JSON in
            in produces?                     Accept Header?
                |                               |
        +-------+-------+               +-------+-------+
        |               |               |               |
       Yes              No             Yes              No
        |               |               |               |
   Serve default        |             Is JSON           |
   login page or        |           in produces?        |
   spa.view, if         |               |               |
   configured           |       +-------+-------+       |
                        |       |               |       |
                        |      Yes              No      |
                        |       |               |       |
                        |   Serve JSON          |       |
                        |   view model          |       |
                        |                       |       |
                        +-----------------------+-------+
                        |
    Pass, developer needs to serve a SPA. Otherwise
    the framework will let this fall through as a 404.
```

I’m very aware of the complexity here, and it looks like a lot of chaos.  But I really do feel that we should support configuration in this way, as it’s a clean way for us to support SPA applications without “Getitng in the way” of the developer’s preferred way of handling their SPA.

The simpler alternative is to move the JSON API to different URLs, and provide some kind of boolean option for disabling the URLs the handle HTML responses.  But I like the simplicity of not having more URLS.

-r out

**Comment by edjiang** [comment]
From the mobile client perspective, I am **very** in favor of having a default /api/\* subfolder, with easy configuration to a separate hostname (api.example.com), that ONLY serves json. 

I also think it's easier for developer discovery, as then they can mess around with the API in-browser, and don't have to configure as many headers when using curl.

**Comment by lhazlewood** [comment]
In the Spring / Spring Boot scenario, there is no 'asset pipeline' to be executed after our controllers.  The controller _is_ the terminal node in the request pipeline, and as such, requires knowledge of what view to render if the default view should not be rendered.  This is a reason why we needed a `stormpath.web.spa.view` value, because controller != filter/middleware.

Are you suggesting we should change our servlet/spring/spring-boot implementation to be filters instead?  That implies some interesting design changes...

**Comment by robertjd** [comment]
@lhazlewood no, I'm not suggesting you have to change to a filter approach :)  I still want to keep `stormpath.web.spa.view`, for exactly your scenario.  What I'm trying to re-define is how our framework responds if `stormpath.web.spa.view` is not present, for those of us who are using filter-based frameworks.

**Comment by lhazlewood** [comment]
For posterity: in today's team meeting we agreed that changing the Java SDK to use filter-based interception rather than terminal controllers would be a better approach, and we'll entirely remove the `stormpath.web.spa` section from config.

The work for the Java SDK to support this approach is here: https://github.com/stormpath/stormpath-sdk-java/issues/542

**Comment by nbarbettini** [comment]
If we end up accepting this solution (which I'm in favor of), we need to circle back around and talk about this: https://github.com/stormpath/stormpath-framework-spec/blob/master/requests.md#supported-verbs

The behavior of returning 405 for unsupported HTTP methods may need to change across the board.
