### ISSUE TITLE
Token Authentication

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-spec#66]
Should we change https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md so it refers to Token Authentication as well? Or do we need to define what token authentication is, and a separate set of responses.

**Comment by robertjd** [comment]
The [authenticators](authenticators.md) document is a stub which lists that authenticators that are responsible for token authentication, but each authenticator still needs a detailed information.
