### ISSUE TITLE
Register Success for JSON

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-framework-spec#69]
Currently, we have the spec saying that we will return a 200 OK response with the root elements of the account (no collection resources)   ...  

I am proposing we change the response code to the 201 CREATED response code as it is more common.

@robertjd

**Comment by robertjd** [comment]
We used 201 in the past, but we removed it because we felt like 201 should be used for an API that is more like a REST-ful API, which the framework API is not.

**Comment by bretterer** [comment]
@robertjd but using JSON, you are treating it in a way like an API (think mobile)

I think it makes sense to do this.

**Comment by robertjd** [comment]
JSON != RESTful.  Further, I'm aggressively fighting un-necessary changes
to the spec, because we already have a lot of work to do.  200 or 201 isn't
really going to matter to the customer.

**Comment by nbarbettini** [comment]
I don't have a strong opinion on this; I'm fine with 200 as it is.

**Comment by robertjd** [comment]
Was this discussed during the last weekly meeting?

**Comment by edjiang** [comment]
Yes, we decided to icebox these two about status codes.

**Comment by lhazlewood** [comment]
FWIW, 200 vs 201 has nothing to do with REST - this is core HTTP stuff.  REST designers just ensured they were adhering to the spec (unlike many bad web applications created over the years). 

As for discussion, I believe we decided to keep 200 and change it after 1.0 - maybe 1.1?  If/when that time comes, we could always default this to whatever we want (my vote would be 201) and allow a config value to change it if desired, e.g. `stormpath.web.login.response.status = 200`.

**Comment by robertjd** [comment]
I certainly want to table this for now, so let's do that.  But while I'm at it: adding a configuration property for this seems totally un-necessary.  Whatever we decide should just be the behaviour.

**Comment by lhazlewood** [comment]
Fine by me - I was only mentioning a backwards-compatible option if app devs actually cared about this - I suspect most won't though.
