### ISSUE TITLE
Logout Response Code

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-framework-spec#71]
Suggestion to change Response code for successful logout for JSON to 204 NO CONTENT instead of 200 OK

**Comment by robertjd** [comment]
We removed 204 because it [causes all kinds of XHR chaos in some browsers](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=xmlhttprequest%20204).  Generally speaking, using simple HTTP codes is the best for browser compatibility.

**Comment by bretterer** [comment]
@robertjd so we are catering to IE 7 and 8 for this issue?

**Comment by robertjd** [comment]
Yes, and recent versions of Opera and older versions of Firefox.

**Comment by bretterer** [comment]
I would like to keep this open.  We should not be supporting these old version.... You cant even install IE7 or IE8 anymore and Opera and Firefox auto update.  The versions of all of these browsers are all EOL

We can discuss internally

**Comment by nbarbettini** [comment]
Side rant: It's pretty silly that browsers don't even handle the normal HTTP spec. 204 isn't crazy by any means.
