### ISSUE TITLE
IDsite

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-spec#73]
We have in the framework spec to kick off the IDSite thing, but not vice versa. Should we add this into the spec for 1.0? Looks like express has a `/idSiteResult` endpoint to take the `StormpathToken`

**Comment by lhazlewood** [comment]
Good point - all SDKs pretty much have this, so yeah, it should be in the spec.

**Comment by edjiang** [comment]
Cool, I'll plan to write this today.
