### ISSUE TITLE
Unauthorized View in Configuration

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-spec#79]
While writing #76 and #78, I noticed a configuration option:

```
    unauthorized:
      view: "unauthorized"
```

This seems to specify a view for an unauthorized error page.

**I think we should remove this** and use the default framework error renderer to render these error pages, which should be more consistent for framework users. 

Also, express-stormpath doesn't seem to be using this and instead renders the view without looking at the configuration option. So I can't find an example of any of our apps that actually use this configuration option. 

https://github.com/stormpath/express-stormpath/blob/master/lib/middleware/groups-required.js#L27

**Comment by nbarbettini** [comment]
I know there was some original reasoning behind it, but it was before my time. I'm interested to hear @robertjd's input.

This hasn't been implemented in .NET yet at all. And I think you're right, it's ignored in express.
