### ISSUE TITLE
web-config.yaml file name?

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-framework-spec#85]
How important is it that the file name be `web-config.yaml`?

For Spring and Spring Boot, a file named `application.yml` will automatically be read. If the file _must_ be named `web-config.yaml`, some defaults will need to be overridden for Spring and Spring Boot.

**Comment by nbarbettini** [comment]
web-config.yaml is just an example - the default file name should be
stormpath.yaml or stormpath.json. (See the SDK Spec section on config.)
