### ISSUE TITLE
Preserve path, query, and fragment when redirecting unauthorized requests?

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-framework-spec#88]
I think [Cookie Authentication#Rejecting Requests](https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#rejecting-requests) should be amended to note that the path, query, and fragment should all be preserved when appending the relative URL to the `next` parameter. The query and fragment should also be properly URL encoded.

Additionally, it wouldn't hurt to clarify the open URL redirection restriction in [Login#POST Response Handling](https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#-post-response-handling), too. (Not a change, just a clarification.)

**Comment by robertjd** [comment]
Meeting today: agreement that we should preserve the route that the user desires to go to, but undecided what the implementation should be (cookie based or URL parameter based).

**Comment by robertjd** [comment]
Also, FYI @nbarbettini, browsers don't send the fragment to the server.

**Comment by edjiang** [comment]
Also for 1.1. 

We will clarify the open url restriction

**Comment by edjiang** [comment]
As a note for the `next` parameter, Facebook seems to be doing that on its login page (although probably whitelisting a set of domains, as I couldn't get it to redirect to non-FB urls):

```
https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fedjiang
```
