### ISSUE TITLE
Missing Cookie max age property in the cookie-authentication spec

### ISSUE THREAD

**Issue by jarias** [stormpath/stormpath-framework-spec#89]
https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md

The max age is not mention in the properties but I think it should be configurable.

@omgitstom If you want I can create a PR for this but probably the other evangelist should at least look at it.

**Comment by nbarbettini** [comment]
We already have cookie expiration defined by the OAuth Policy:

> The `expires` flag should be determined by the `ttl` value for the token, as defined by the Oauth Policy of the Stormpath Application.

Is there any reason we should use max-age instead of expires?

**Comment by jarias** [comment]
Thanks @nbarbettini I miss that, closing this

**Comment by nbarbettini** [comment]
No prob :smile:
